### ISSUE TITLE
Wallet Address font on Sheikah is confusing/misleading

### ISSUE THREAD

**Issue by tomsanch** [witnet/sheikah#1591] opened 2020-12-30 15:42 UTC
Numerous Republic claimers misread their wallet address when copying it. Specifically, mixed up lower case "L" with "1"

**To Reproduce**
1. Go to Sheikah interface
2. Create new address
3. Observe "L" could be mistaken for "1", as per screenshot below

**Expected behavior**
It may be solved with the same font, but _non-italicized_, or a new font is necessary which better differentiates between "L" and "1"

**Screenshots**
https://imgur.com/a/pwkA85k

**Comment by aesedepece** [comment] 2020-12-30 17:12
Duplicate of #1590

**Closed by aesedepece** 2020-12-30 17:12 UTC
